const m=require("./maths")
const n=require("./mdl")
console.log(m.add(7,8))
console.log(m.sub(17,8))
console.log(m.mul(7,8))
console.log(m.div(8,8))
console.log(n.evnod(17))
console.log(n.tbl(5))